### ISSUE TITLE
Set up workflow document

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#1]
Just steal our Oregon Digital workflow?

**Comment by karindalziel** [comment]
Yes oregon digital

**Comment by jechols** [comment]
https://github.com/open-oni/open-oni/wiki/Development-Standards

This is mostly stolen from the OD stuff, which itself is OSU's internal practices.  I rewrote some of it to reflect things like this project being django-based.

@open-oni/developers: I have questions here:

- Do we all like the document?
- Do we want this on the wiki or do we want an in-repo file?  Wiki means easier editing, but maybe that's a bad thing for a dev standards document.
- Is there anything else the document should cover?

**Comment by karindalziel** [comment]
I move that we all accept these standards, they look good to me. Will bring up in phone call to see if there are any objections.

**Comment by jechols** [comment]
Closing - reopen or start a new issue if there are concerns
