### ISSUE TITLE
Issue Navigation drop-down does not update page metadata

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#10]
from chronam: https://github.com/LibraryOfCongress/chronam/issues/115

Any time one uses the Image (page navigation) drop-down on the Chronicling America page view to browse from image X to image Z – the metadata and image navigation doesn’t change/keep up.

Note: it’s the issue navigation that seems to be the problem. Navigating between search results using links does update the metadata correctly…

Example:
http://chroniclingamerica.loc.gov/lccn/sn89066617/1915-01-22/ed-1/seq-1/

Select Image 2 in drop down and you come to this page:
http://chroniclingamerica.loc.gov/lccn/sn89066617/1915-01-22/ed-1/seq-2/

However the title metadata displays as:
The weekly tribune and the Cape County herald., January 22, 1915, Image 1

Furthermore, trying to move beyond that second page to image 3, presents a blank screen.

This was reported by an NDNP awardee and replicated by Serials staff.

**Comment by karindalziel** [comment]
persistent url does not update either

**Comment by jduss4** [comment]
@karindalziel I believe this was fixed here?  https://github.com/open-oni/open-oni/commit/ad6368e1a23f78079086f513adbc2452acaeb65c

Can you confirm?

**Comment by jechols** [comment]
I'm certain this was fixed.  By taking out the JS magic in the page loading, the links are now real links that actually direct to a real page.  No magic, no bugs.

**Comment by jduss4** [comment]
@jechols there is still a little jquery magic, because it's firing off here:  https://github.com/open-oni/open-oni/blob/f34f11d5127b17177c2ed848cf80cb9a1c7051c3/core/static/js/page.js#L142

but I think you're right that all the magic was taken out, so it seems to be working fine when I tested it on open oni's master branch
