### ISSUE TITLE
Discuss forms, accessibility, and usability

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#101]
we need to have a discussion around the best way to allow users to search for and refine results. 

From Nebraska: 

<img width="895" alt="screen shot 2016-01-28 at 3 07 16 pm" src="https://cloud.githubusercontent.com/assets/284315/12658813/f2ab83c4-c5d0-11e5-9439-ed44876a2ae9.png">

<img width="1197" alt="screen shot 2016-01-28 at 3 07 05 pm" src="https://cloud.githubusercontent.com/assets/284315/12658815/f72b6aa4-c5d0-11e5-901f-a3a4cffad772.png">

There are quite a few accessibility and usability problems with our approaches: tab order is not set, auto jump menus are used, etc. We'll have a few improvements after the Jan 2016 open-oni sprint, but not nearly enough. 

Please sign (by commenting) on if you are interested in this discussion!

**Comment by techgique** [comment]
Sign me up!

**Comment by jechols** [comment]
Always keen to discuss accessibility, though I'm far from an expert.

I'm useless where usability discussions are concerned, though....

**Comment by edsu** [comment]
:+1:

**Comment by AndrewGearhart** [comment]
:+1:

**Comment by windrant** [comment]
I'm certainly interested in the usability end of things. We have had LOTS of feedback over our search interface and what we use now is a reflection of that. It still need improvement. Accessibility is probably horrid. It's awful on mobile screens... but we don't use any responsiveness anyway.

**Comment by jduss4** [comment]
#213  #205 #294
