### ISSUE TITLE
Don't cache the site in debug mode

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#103]
If we decide `DEBUG = True` means development mode, we should make the site default to not caching by checking `DEBUG` in `settings.py`.

We should set caching to something only if it isn't already set so that `settings_local.py` can still force it into a set mode.  We should check `DEBUG` and the cache settings only after all global and local settings have been read.

**Comment by techgique** [comment]
I think #361 handles this well enough with the `settings_development.py` and `settings_production.py` cache settings while still allowing override in `settings_local.py`.

It also doesn't link any of the settings to each other which I think could get confusing.

**Comment by techgique** [comment]
Implemented here: https://github.com/open-oni/open-oni/blob/c273b46472151ae7a191fc2a019f1dcb42c98287/onisite/settings_local_example.py#L184
