### ISSUE TITLE
Figure out base theme

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#11]

**Comment by jechols** [comment]
And example subtheme

**Comment by duncanbarth** [comment]
Base theme needs minimal functionality in a non-site specific way.
Example subtheme has examples of all features, theme overriding, etc.

**Comment by jechols** [comment]
We need to look into how overrides can happen without copying entire python files.  Modifying URLs should be easy, too.

**Comment by jechols** [comment]
Simplify templates to ease editing (without losing granular overriding)

**Comment by jechols** [comment]
Document basic page structure for building templates that are easy to override

**Comment by karindalziel** [comment]
Not in January codesprint because I think I'll spend all my time on a generic theme that can be used as a base. If I finish that I'll work on sub themes.

**Comment by jduss4** [comment]
@karindalziel should this be considered done?

**Comment by jechols** [comment]
I think we need wiki docs first, per a comment I made almost exactly a year ago :P

**Comment by jduss4** [comment]
heh sounds good

**Comment by jduss4** [comment]
I filled out some documentation on creating your own theme and overriding content / blocks.  I did not work on anything CSS related in it, however:

https://github.com/open-oni/open-oni/wiki/Theming

**Comment by jechols** [comment]
I think we're in a good position now, closing.
