### ISSUE TITLE
Don't assume there are 20 pages present on the homepage

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#113]
I didn't pay close attention when merging, but the homepage code now randomly picks a single issue to display, and assumes there will be 20 of them available.  This doesn't work when there are fewer than 20 issues and the random number is too high.  Probably better to have the random number capped at the issues returned by the frontpage issues function.

**Comment by jduss4** [comment]
Good point.  I'll fix this.

**Comment by jduss4** [comment]
This is addressed by this PR:  https://github.com/open-oni/open-oni/pull/114
