### ISSUE TITLE
Track down "TypeError: can only concatenate tuple (not "instance") to tuple"

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#115]
Seems to have started hitting after frying essay code - may require killing data volumes to reproduce this, as I don't recall seeing it until I recently cleaned up a bunch of docker stuff.

**Comment by jechols** [comment]
Fix, courtesy of @jduss4 : `option_list = BaseCommand.option_list + (pull_title_updates, )` in title sync.  But this creates a new oddity where we get thousands of warnings like this: `WARNING:openoni.core.management.commands.title_sync:Unable to load place with name ...`

I know where the warning comes from in the code, but I'm not sure why this is an issue to begin with.

**Comment by jechols** [comment]
My latest assumption is that we have to load a batch to get data in the system so it doesn't try to keep reinstalling fixtures.  No idea if that's it, but I have to stop digging into this right now.

**Comment by edsu** [comment]
That's an error from the title loader [saying](https://github.com/open-oni/open-oni/blob/master/core/management/commands/title_sync.py#L148) it wasn't able to link a place name subject in the MARC data to a known place in the database (loaded from the place_links fixture).

**Comment by jechols** [comment]
I lied, I had time to load a batch.  It appears that loading a batch causes fixtures to stop attempting to load.  No clue here.

@edsu, thanks.  I still don't really know what to make of the error, considering I had no data at the time of those warnings.  Once I loaded a batch, the next `./dev.sh` run was fine.

Oh, interesting: `WARNING:openoni.core.management.commands.openoni_sync:Database or index not empty as expected.` - after you load data, it doesn't try to do its data sync?  Maybe we need to learn more about this sync process.

**Comment by edsu** [comment]
Yes, chronam_sync was really just for setting up and initializing the database.

**Comment by jechols** [comment]
This needs some attention so we can either stop running the sync multiple times or stick something in the sync that auto-aborts *without* errors when it's already been run.

**Comment by jechols** [comment]
This is gone - we stopped using the sync task due to a variety of problems with it, notably it didn't play nicely with the new way django handles migrations
