### ISSUE TITLE
test search within API

### ISSUE THREAD

**Issue by srabun** [open-oni/open-oni#131]
Can Open ONI test some of the search API work that is happening for IIIF?

see reference: https://docs.google.com/document/d/14-5Pwi7AOAtXM4jjiPNsrCP-qYlIE4msCWzIigY3rtk/ 

broader notes: https://docs.google.com/document/d/1hOJYtppNNFkUitsuM_ilb2slX_z_g77RTnv7GdQc64E/edit?usp=sharing

**Comment by jduss4** [comment]
@srabun I assume this is no longer something you need tested?  Sorry that we didn't get to it sooner... :(

**Comment by raybrarian** [comment]
Close - not enough information to go forward.
