### ISSUE TITLE
Figure out what documentation we need to write

### ISSUE THREAD

**Issue by duncanbarth** [open-oni/open-oni#14]
Django cheatsheet?
Day-to-day running the app?
Theming howto?
Deployment guide?

**Comment by jduss4** [comment]
This might be a start:  https://github.com/CDRH/nebnews/tree/master/docs

**Comment by karindalziel** [comment]
Part tech and part non tech. We can make this a wiki page - a wishlist of documentation.

**Comment by usctcl** [comment]
I'm happy to assist with any documentation development.
