### ISSUE TITLE
Add HTTPS?

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#142]
There was a request for HTTPS for chronam on the mailing list. This might be a good thing to add to open-oni, and hopefully wouldn't take too long.

**Comment by jechols** [comment]
Supporting https in the software really just means fixing the code to not hard-code the protocol.  If that's what you're talking about, yes, this is probably not a huge addition (though the http protocol is hard-coded in a surprising number of places).  In fact I think the server's base URL should just be a config setting to begin with so it could be http or https, running in a subpath or the server root, etc.

But making it https-ready is all we can do on the software side.  Whoever stands up an oni instance will have to decide to put in the time to get a cert and configure apache properly.  We could make it so there's a warning when it is run under http, but we can't do much to ensure people are actually running it securely.

**Comment by karindalziel** [comment]
Yeah, that's what I was thinking. We can include some suggestions for apache config, at least, or maybe examples.

**Comment by techgique** [comment]
HTTPS everywhere or bust!
I like the idea of adding a warning with a link to suggested Apache config.

**Comment by AndrewGearhart** [comment]
Perhaps even provide suggestions for utilizing https://letsencrypt.org/ ?
I would love to investigate what it would take to use LEo to encrypt all traffic.

**Comment by jechols** [comment]
Making the base URL configurable was already a ticket: #128 - should we close this ticket?

**Comment by jechols** [comment]
Base URL is now configurable.  We probably need some docs on how to set up https, but that's not really an ONI problem as much as a "how much hand-holding do we have time to do" kind of problem.  If anybody wants to tackle that, I say pop something in the wiki.
