### ISSUE TITLE
Make docker setup better

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#143]
1. Look into docker-compose.  I'll be doing some deeper docker diving before our next sprint for a different project, so maybe I can help here.
2. Look into named volumes instead of data-only containers: http://stackoverflow.com/questions/36011595/docker-named-volumes-vs-doc-data-only-containers and https://docs.docker.com/engine/reference/commandline/volume_create/

1 gives us a much easier dev.sh script and setup instructions, and 2 gets rid of several problems with our data-only containers, such as not knowing which volume holds what data, and losing data if we remove a container.  Containers are meant to be removable without side-effects, after all.

**Comment by jechols** [comment]
Moved to MVP since we'll need better dockerizing to go prod

**Comment by jduss4** [comment]
docker-compose is implemented, @techgique will be working on production deployment.  Closing issue in favor of opening more specific current issues.
