### ISSUE TITLE
Migrate solr 4.10 to solr 6

### ISSUE THREAD

**Issue by jduss4** [open-oni/open-oni#145]
The docker setup is using solr 4.10, which is the final of the 4.x versions. The latest solr is 5.4.0 but the migration won't be trivial:
https://cwiki.apache.org/confluence/display/solr/Upgrading+a+Solr+4.x+Cluster+to+Solr+5.0
https://cwiki.apache.org/confluence/display/solr/Moving+to+the+New+solr.xml+Format

General guide
https://cwiki.apache.org/confluence/display/solr/Upgrading+Solr

**Comment by jechols** [comment]
Per the oni slack conversations, we're going to upgrade to solr 6.  I'm working on this.
