### ISSUE TITLE
Examine and possibly fix all references to loc.gov

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#147]
Even when we get the majority of hard-coded URLs out of the app, there are still places we need to do more investigation to see if we want loc.gov to be the URL.  Some docs should probably point to loc, but others should point to the local site.  Some XML feeds claim the author is loc, and probably should change, but maybe they should stay loc since loc is in fact the original author...?

**Comment by jechols** [comment]
`core/templates/reports/terms.html` needs to be looked at - seems like references to LC terms should just go to LC and never be part of an ONI instance, since the terms are in fact defined by LC.

**Comment by jechols** [comment]
`core/middleware.py` shows images from LC when the site is too busy.  That whole HTML output should be rewritten probably.

**Comment by jduss4** [comment]
`core/middleware.py` has been un-LC-ized by simply display a generic error message.  But no boat.  :(

**Comment by jduss4** [comment]
I would find it entirely reasonable to have a `terms.html` page that simply links to the LoC version of the terms, rather than worrying about maintaining something which is basically just mirroring their descriptions anyway

**Comment by AndrewGearhart** [comment]
I don't think we should offload the terms.html page to LC. See #166 (ability to make local changes to terms).

**Comment by raybrarian** [comment]
Closing issue - new issues should be reported for specific pages.
