### ISSUE TITLE
Look into project structure

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#150]
I'm seeing documentation that sort of suggests that our project structure maybe isn't what it should be... maybe.  There's still a lot of investigation, but here's what I *think*:

- Our structure is forcing us to have a single `urls.py`, which makes minor additions impossible without code overrides
- The newer structure has a separation of projects from apps, which I don't fully understand, but seems to suggest that "apps" are ways to compose functionality, which could ease things like branding
- Migrating to the newer structure won't be hard, but it will touch literally every file, so it should happen between sprints if it's something we want

**Comment by jechols** [comment]
https://docs.djangoproject.com/en/1.9/releases/1.4/#updated-default-project-layout-and-manage-py

**Comment by jduss4** [comment]
We may need this to be MVP if it means that we have more flexibility with custom themes / no code rewriting in core.

**Comment by jechols** [comment]
@techgique, tagging you so you get my updates

**Comment by jechols** [comment]
New info here - it looks like in one of the official tutorials, there's a suggestion that site-level template overrides live in a `templates` directory off the project root.  It doesn't seem like that would work for anybody who needed custom CSS or JS, but maybe there's a way to add magically included static files.  If so, we could get theming completely separated from "plugins" (ONI-specific apps, in the django nomenclature), and theming would be much simpler for the end user.

**Comment by jechols** [comment]
Sadly, most code is going to have changes, just because so many import paths used to be "openoni.core" and the new structure puts core at the top.
