### ISSUE TITLE
What is conf/openoni-canonical.conf?

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#151]
I think it's a file that wants to be removed.

**Comment by jechols** [comment]
> Update the KeepAlive directive in /etc/httpd/conf/httpd.conf config from 'Off' to 'On'. If you are the Library of Congress you will also want to canonicalize URLs that used by the Chronicling America application at the Library of Congress:
>
> sudo cp /opt/openoni/conf/openoni-canonical.conf /etc/httpd/conf.d/

So it's just for LC.  Oni probably won't work for LC since it's going to be state-centric.  Let's kill that file.

**Comment by techgique** [comment]
Yeah this seems fair to fry if we're going to rewrite Apache config / instructions. Just don't want people to lose the directive for canonical URLs if they are serving with multiple vhosts. :-)

**Comment by jduss4** [comment]
https://github.com/open-oni/open-oni/pull/172
