### ISSUE TITLE
Revisit template URLs

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#152]
In order to remove hard-coding of URLs, and to get it done fast, most work was just done via blind string replacements.  But there are a lot of places where we simply don't need the host at all, and instead could use a path relative to the hostname.

This is "easy" unless we want to worry about #148, where the app is actually running on something like "https://example.com/oni".  If we tackle that, we're going to need a base path separately from the base url.

**Comment by techgique** [comment]
We sometimes refer to that part as a 'sub-uri' as well, but BASE_PATH is probably a more widely used name for it?
Either way, it's understood and noted. Good point.

**Comment by jechols** [comment]
Hah, don't assume *I* know proper terminology.  To clarify, here's what I think would cover all our bases:

```
PROTOCOL = "https"
HOST = "example.com"
BASE_PATH = "/oni"
BASE_HOST = PROTOCOL + "://" + HOST
BASE_URL = BASE_HOST + "/" + BASE_PATH
```

Most things would use BASE_URL or BASE_PATH, but BASE_HOST may be needed, too.

And now I hate the word "base".  Hmm.

Variable names may or may not be legit, and somebody more devoppy than I should decide if they should change.

**Comment by techgique** [comment]
Your `BASE_URL` example would be `https://example.com//oni` ;-)

I think I might write this like:
```python
PROTOCOL = "https"
HOST = "example.com"
WEB_ROOT = "/oni"
HOST_URL = PROTOCOL + "://" + HOST
BASE_URL = HOST_URL + WEB_ROOT
```

I don't know. I'm not 100% on whether I like those names or not.

**Comment by jechols** [comment]
Yeah, good catch on the double-slash!

I don't care about names, yours seem better than mine :)

**Comment by techgique** [comment]
Maybe `WEB_URL` for that last one. Completes the pattern more nicely, don't you think?

**Comment by jechols** [comment]
I'm okay with WEB_URL, though it would mean a ton of files touched to fix it.  Maybe a post-sprint cleanup or something.

**Comment by jechols** [comment]
Oh, forgot this is a bigger task than this sprint anyway.  So whenever it's done, probably good to do it while not many others are working on it.

**Comment by jechols** [comment]
It's looking like if we fix the app to only generate URLs through django, we could just advise people to hook `core.urls` to a different url in `onisite/urls.py`:

    # Instead of this
    url('', include("core.urls")),
    # Do this
    url('^subpath/', include("core.urls")),

Pretty sure that would do it if we had all URLs generated properly.

**Comment by jechols** [comment]
May have a lot of overlap with #230
