### ISSUE TITLE
Docker containers?

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#17]

**Comment by mark-cooper** [comment]
Ready and available at:

https://github.com/open-oni/docker-open-oni

Close this after?:

https://github.com/open-oni/docker-open-oni/issues/1

**Comment by jechols** [comment]
I think we can call this good!  If there are any docker-related issues from this point forward, we can open new tickets, and probably on that new repo.

I'm not sure about that other ticket - I think maybe @karindalziel needs to weigh in on whether it's good (I'm not actually sure I know what that ticket is all about).

Thanks for the docker stuff, though, @mark-cooper!
