### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by jduss4** [open-oni/open-oni#170]
Try to get a tool up and running that will give us an idea of test coverage
First step is probably investigating what the best tools are

http://django-testing-docs.readthedocs.io/en/latest/coverage.html

**Comment by jechols** [comment]
Well, here's some bad news: https://github.com/django-nose/django-nose/issues/231

I'll keep trying, but we might not get django-nose to play nicely with our setup.  That bug's been sitting for nearly a year.

**Comment by jechols** [comment]
...

I may have a "fix".  But it's ugly.  I'll report more tomorrow.  If I'm still sane.
