### ISSUE TITLE
Fix inconsistant wording on Newspaper Title page

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#175]
From Newspaper Title view page, make first issue and last issue jump to issues page not individual pages. 

Or, change wording, though this might be awkward "jump to first page of first issue"  "jump to first page of last issue."

Or, we might decide it's not a big deal and skip it.

**Comment by jduss4** [comment]
Of this choices I think I would prefer jumping to the issue pages instead of the individual pages.  That makes the most sense to me from a browsing perspective.
