### ISSUE TITLE
Consider what to do with "Newspaper Directory" section

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#176]
I have removed the newspaper directory template, but we will need to determine if any piece of this is something we'll want to work into other templates (like the search). 

https://github.com/open-oni/open-oni/commit/b240a3cd492357c6cd4df406e4da21799df9d63f
https://github.com/open-oni/open-oni/commit/974e2743203e343415882eb0491c27c6006226f9

I am not clear on whether this was searching the same database info as the normal search, or if there was a different set of database results.

**Comment by jduss4** [comment]
I think that this issue is related enough to #193 that I'm going to close this one
