### ISSUE TITLE
Nonexistent Settings

### ISSUE THREAD

**Issue by jduss4** [open-oni/open-oni#179]
Two settings show up in the code which are not set up currently in the `settings_base.py` file

**WORLDCAT_KEY**
- `core/title_pull.py`
- `core/management/commands/title_sync.py`

**PROFILE_LOG_BASE**
- `core/decorator.py`

In two cases, if the setting doesn't exist it won't break the code, but in `title_pull` it looks as though there might be a problem.

We should evaluate the files and decide how to handle the settings.

**Comment by jechols** [comment]
Regarding the title pull: I feel like these kinds of services belong outside of "core".  Maybe it shouldn't even be in the app at all, I'm not sure.  It's a pretty custom feature that we have no way of testing at the moment.  I'm all for getting at MARC records more easily, but the title puller seems to be anything but easy.

**Comment by jechols** [comment]
That profile thing seems to be dead code.  I can't find anything in the app (*.py or *.html) that references it.

**Comment by jduss4** [comment]
I agree that we should just take out the title puller code if we are not planning on supporting it / testing it
