### ISSUE TITLE
Investigate external dependencies

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#18]
Look for stuff that calls other stuff that isn't local

**Comment by duncanbarth** [comment]
for example, chronam-sync, does it need to pull data to prepopulate tables?

**Comment by jechols** [comment]
Back-end and front-end research probably needed

**Comment by karindalziel** [comment]
For a first step, we just need a list. Then we ned workarounds for at least some of the external calls, probably.

**Comment by jechols** [comment]
I'm going to slowly write up a document with everything I find.  There are a *lot* of red herrings, so this one might take the rest of my time this sprint :(  I'm hoping to fix obvious problems as I go, though, rather than just writing things down - for instance, there are a ton of "external" JSON calls that are actually just routing back to the app.  These could just return the JSON as-is instead of adding the extra HTTP hit, and thereby reducing the appearance of external requests.

**Comment by edsu** [comment]
Note: some of those external JSON calls back to the app are sometimes there because the query can take considerable time to compute and the result can be easily cached at the http level.

If I were you I would focus on obviously external web resources, if I am understanding what you mean by *dependency* correctly.

**Comment by jechols** [comment]
Well at the least, that should be documented, and the "host" field should be required, not defaulting to chroniclingamerica.loc.gov.  It gives the impression of an external resource when there shouldn't be one.

**Comment by jechols** [comment]
Preliminary investigation of EVERY occurrence of "http": https://github.com/open-oni/open-oni/wiki/HTTP-in-the-code

**Comment by jechols** [comment]
I think there are some obvious things I can knock out - for instance, unused variables that pretend we're using external vars.  I'll cross things off that list if I do deal with them.

**Comment by jechols** [comment]
Regarding the JSON - I was misreading it.  I saw `HttpResponse` but got it in my head it was making an HTTP *request*.  I think there is no extra hit there.
