### ISSUE TITLE
Advanced Search by Title

### ISSUE THREAD

**Issue by jduss4** [open-oni/open-oni#180]
Pull out the functionality from the US Newspapers Directory and put it into the advanced search

Step One will be Jessica hacking it in
Step Two will be Karin making it useable

**Comment by jduss4** [comment]
Related to https://github.com/open-oni/open-oni/issues/93

**Comment by jduss4** [comment]
Is that already done here?
<img width="606" alt="image" src="https://user-images.githubusercontent.com/2480492/44421388-fbc33180-a545-11e8-89b9-7be6b0e43665.png">

Or are we talking about the lccn?

**Comment by raybrarian** [comment]
Completed.
