### ISSUE TITLE
Figure out settings file

### ISSUE THREAD

**Issue by duncanbarth** [open-oni/open-oni#19]
Add comments to settings file document what each settings do (and rip out settings that don't actually do anything)

**Comment by jechols** [comment]
(Note that comments here are likely just to remind myself of things since I will be doing other work on and off)

The file has internal settings for django as well as settings related to chronam.  The django settings info can be found at https://docs.djangoproject.com/en/1.8/ref/settings/

**Comment by jechols** [comment]
I don't like having all these settings in on file.  It makes it a pain to differentiate settings that are sensitive, settings that are core django values, and settings that control the app.

It would be trivial to have multiple cascading settings files, I think.I will need to test this out, but I like the idea of:

- settings_django.py
- settings_oni.py
- settings_local.py

`settings_local.py` would be created on initial install via some admin task, and wouldn't be in source control.  (Or could we just import it conditionally?)  `settings.py` would then combine these three files via imports like this: `from settings_django import *`.  As long as the order is the same as above, local settings could override or just add to the other settings files.

**Comment by jechols** [comment]
Looking at django settings, we'll definitely need an easy way to override settings that isn't in the repo.  The timezone setting alone necessitates some kind of elegant override process.

**Comment by jechols** [comment]
@techgique suggested this as a possible model: https://code.djangoproject.com/wiki/SplitSettings#Multiplesettingfilesimportingfromeachother

**Comment by edsu** [comment]
:+1: for overriding with settings_local.py using that pattern.
