### ISSUE TITLE
Search Pages Results Additional Facets

### ISSUE THREAD

**Issue by jduss4** [open-oni/open-oni#191]
Plug in the same faceting that Nebraska has, plus more?

city, frequency, (state?), county, (year range?)

**Comment by jechols** [comment]
@jduss4 is this done?  Or were you talking about something more elaborate than the dropdowns?  (Which I want to figure out, just wasn't sure if this ticket was that)

**Comment by jduss4** [comment]
Looks like
- county
- city
- frequency

are already in open oni

year will be added by #333, so then I think the only one we would still need for Nebraska is language

**Comment by jduss4** [comment]
#340
