### ISSUE TITLE
Test investigation

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#2]
Do we want to keep current tests?  Rewrite?  Start fresh?  Need to determine test coverage goals.

**Comment by karindalziel** [comment]
Leaving this milestone 1 for now, as there is not much use doing this unless we get some of the other things fixed.

**Comment by jechols** [comment]
Update: I'm hoping to have all current tests passing this sprint.  Figuring out what other tests we need, how to measure test coverage, etc. is probably not going to happen for a bit.
