### ISSUE TITLE
Discuss Advanced Search

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#205]
![advaned_search_form](https://cloud.githubusercontent.com/assets/284315/16992681/ede906ae-4e65-11e6-82c2-67c966a4734e.JPG)

**Comment by karindalziel** [comment]
Some notes: the "show/hide search examples" will be collapsed by default. The "Search only the following newspapers" will have some kind of toggle so you can choose if it is shown by default (ok for small #'s of papers, too long for large #'s)

The "Search terms" box takes the place of the 4 different kind of searches currently provided, with examples showing how to format the search (basic solr searching)  It replaces this: 
![screen shot 2016-07-20 at 10 39 29 am](https://cloud.githubusercontent.com/assets/284315/16992772/458f27ee-4e66-11e6-8418-47a0771d818e.png)

State will be optional, since many of these installs will be single state. We may want to provide an optional block override on all elements.

**Comment by jechols** [comment]
FYI, that search terms box may require extra coding on our end.  I don't know a ton about solr, and it seems like you can't inject destructive data, but you can submit crazy queries that we might not want to run (too much CPU or something).  So I don't think we should just send whatever they supply straight to solr.  But if we don't, that means our code is having to parse whatever magic we offer in the single search field.

For simple search, one search field makes sense.  But for the advanced search, I'm inclined to leave the fields as-is since we know they work and the backend isn't changing.

**Comment by karindalziel** [comment]
@jechols Hmm. I'm not sure because we're certainly not solr experts, but I think it would probably be ok? I mean, even with the size of our indexes we're probably not bumping into the high end of what a single solr instance can handle. that said, or instance is not near as big as yours. 

If we go with separate fields though can we drop the "5 words within" one? That doesn't seem to work for us anyway and I find it awkward. It's weird they supplied that and not one way to do a NOT. 

So in that case we'd have:
* ANY of the words (the top one and default)
* ALL the words
* Phrase

**Comment by jechols** [comment]
I think that's more your decision (and other stakeholders like @srabun) than mine - I just wanted to point out the potential downsides :)

**Comment by jduss4** [comment]
related to https://github.com/open-oni/open-oni/issues/98

**Comment by jechols** [comment]
Info about solr security: https://wiki.apache.org/solr/SolrSecurity and https://cwiki.apache.org/confluence/display/solr/Basic+Authentication+Plugin

It sounds like the safest bet is not to accept raw solr queries.  Barring that, we'd need a proxy with at least some basic sanity checking, and a read-only user connecting to solr so if our input validation fails there is absolutely no chance of a destructive operation.

**Comment by jduss4** [comment]
At least for now, I'm not going to mess too much with HOW the search works, but simply plug more filters in where possible!

**Comment by karindalziel** [comment]
I think this can be closed. By the time we get around to implementing a new search tech will have changed enough that we will want to revisit anyway.
