### ISSUE TITLE
Reports Pages Broken

### ISSUE THREAD

**Issue by techgique** [open-oni/open-oni#210]
Visit `/reports`

Looks like these pages are broken:
States View: `/states/`
Batch Feed: `/batches/feed/`
- Label should probably be "Batches Feed"?

Events Feed: `/events/feed/`
Newspapers Feed: `/newspapers/feed/`

**Comment by jechols** [comment]
Can you define "broken" for each of the things you say are broken?  My states report does seem to be broken (or at least, it doesn't show anything for some reason).  But my batch feed seems to be all right, unless the title is the only problem you had with it.  My events and newspaper feeds also both seemed to be fine.

**Comment by jduss4** [comment]
#343 related

**Comment by raybrarian** [comment]
Is this still an issue? If not, it can go to the Wishlist milestone!

**Comment by jechols** [comment]
Most data here is likely available in other formats / URLs. If @techgique is okay I'd like to close it....

**Comment by raybrarian** [comment]
closing - will use #343
