### ISSUE TITLE
Form Overhaul

### ISSUE THREAD

**Issue by jduss4** [open-oni/open-oni#211]
Right now there are several forms which are sometimes inheriting from another form but it doesn't seem very streamlined.

Here is my proposal.

At the top of the file, we have the same kinds of default values and helper methods that currently exist.

Then we have a very generic default form with all the fields that anybody might want for searching / browsing filters, plus an **init** that sets some values that can be passed into the user

``` python
class FormBase(forms.Form):
    state = fields.ChoiceField(label="State", choices=STATE_LIST)
    city = fields.ChoiceField(label="City", choices=[])
    etc

    def __init__(self, *args, **kwargs):
        self.fields["state"].choices = kwargs.get("facets_state", STATE_LIST)
        self.fields["state"].initial = kwargs.get("state", None)
        self.fields["city"].choices = kwargs.get("facets_city", None)
        self.fields["city"].initial = kwargs.get("city", None)
```

Then each page would have its own form that could manipulate those further, but generally would leave them alone?

``` python
class SearchPagesForm(FormBase):
    # switches from choice to multiple choice
    state = fields.MultipleChoiceField(choices=STATE_LIST)

    def __init__(self, *args, **kwargs):
        super(FormBase, self).__init__(*args, **kwargs)
        self.fields["city"].label = "Search By City:"
```

Does this make sense?  I think there would still be quite a bit of customization, but not having to repeatedly set languages, locations, etc, from facets would be very nice.  Also, besides a few fields (row, sort, which were tests) nearly all the dropdowns' initial values are being set in the template, though we could easily set them in the form by putting this in the view:

``` python
form = forms.SearchResultsForm({"rows": rows, "sort": sort})
```

**Comment by techgique** [comment]
So we have a sort of uber-form as the base, and one can create a subclass and trim down to just the fields one wants?

**Comment by jduss4** [comment]
I'm not thinking of it so much as trimming, because you have to "opt in" in the actual templates, but more of customizing and adding?

Mostly I want to avoid the current practice which is to redefine each field several times over in each of the forms.

**Comment by raybrarian** [comment]
Did any of this get remediated when the improvements were made to search?

**Comment by raybrarian** [comment]
Possible to look at in the future, but closing for now.
