### ISSUE TITLE
Discuss Search Results Faceting

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#213]
![example faceting](https://cloud.githubusercontent.com/assets/284315/17000955/a3639200-4e8a-11e6-9a40-133e691fbc84.png)

**Comment by karindalziel** [comment]
This is a proposed handling of the search results page that will allow the user to facet/adjust their search.

**Comment by karindalziel** [comment]
as requested by @jduss4 here is a link to my super ugly HTML for this: 

https://gist.github.com/karindalziel/89d0c5a0971413b6e9e5b79de47545e3

**Comment by jduss4** [comment]
#338
