### ISSUE TITLE
Rename chronam to open-oni

### ISSUE THREAD

**Issue by duncanbarth** [open-oni/open-oni#22]
Many places in the code, etc. refer to the product as chronam (e.g. file paths, configuration files, names of libraries, theme, etc.).

Renaming everything is likely non-trivial, but we should figure out what we want to do.

**Comment by jduss4** [comment]
I started working on this.  So far, the software seems to be running okay.
https://github.com/open-oni/open-oni/pull/56/files
https://github.com/open-oni/docker-open-oni/pull/3
