### ISSUE TITLE
Fix URL paths

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#230]
The URLs on the about_api page have very broken paths.  Some paths are hard-coded.  Some are using built in the models themselves.

The models are building URLs manually in a lot of places (search for "json_url").

In both situations, we end up with URLs that don't respect mounting `core` under a non-root path.  For instance, change your `onisite/urls.py` file to contain this:

```
url('^oni/', include("core.urls")),
```

Then browse to your site with "/oni" on the end.  Most things work, but the majority of examples on the About API page are broken.  We need to make _all_ URLs get generated by proper django helpers.  This probably means fixing the about page similarly to what was done in commit 9c850a452c58f00a988b44436471ec730f4b6c5e.  It also probably means removing all those model helpers that generate URLs.  That kind of logic belongs in views and/or templates to begin with, and definitely needs the django helpers, not just a raw `BASE_URL` combined with a path.

**Comment by raybrarian** [comment]
Need to see if this is still an issue.

**Comment by jechols** [comment]
This needs some review - we need to determine if this is a problem still, and if so, what needs to be fixed.

**Comment by raybrarian** [comment]
Also #152

**Comment by raybrarian** [comment]
Closing - more of an edge case issue.
