### ISSUE TITLE
Discussion of navigation for default/core

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#235]
The Navigation bar as is is getting a little full, and does not have everything we want. Here's the current navigation: 

![screen shot 2016-07-26 at 9 26 38 am](https://cloud.githubusercontent.com/assets/284315/17141774/15f9404e-5313-11e6-9367-0c593c4f2e58.png)

In order for Nebraska (and possibly Oregon) to launch, we'll need to add an option for "Map" (On the NE website it's called "City"). Nebraska also has "publishing history" but has split the nav into two because it was too long. 

I think it would be ideal for the default nav to fit all on one line if possible. It may wrap, but the break should then make sense. 

Karin's Proposed navigation:
- Home
- Newspapers
- Date
- Map (or place - thoughts?)
- About
- Help 
- search bar with cities option
- Advanced search

Note: I dropped "API" (that can go in about)

I'm also pondering how aspects of navigation might be overwritten: includes really limits this, so I may go back to included templates.

**Comment by jduss4** [comment]
Since this issue is 2 years old and we have working nav for openoni that three states have based templates on, I am going to take the liberty of closing this issue
