### ISSUE TITLE
Admin command to manage plugins?

### ISSUE THREAD

**Issue by jduss4** [open-oni/open-oni#237]
@jechols brought up the idea of managing plugins via a command:

`manage.py get_plugin https://github/....`

Consider the possibilities / drawbacks of this.

Ideas:
- download
- update
- removal
- list all available plugins
- create an empty plugin (basic file structure with some instructions in README)

**Comment by jechols** [comment]
I think this would be pretty slick, obviously, but I think we have to first figure out if our optional plugins even make sense outside ONI, given that we can't test them without ONI's context.  Maybe that's a discussion for the sprint review.

**Comment by jechols** [comment]
This is too pie-in-the-sky
