### ISSUE TITLE
Switching Between Themes Assets Loitering

### ISSUE THREAD

**Issue by jduss4** [open-oni/open-oni#238]
If you install a new theme (for example: https://github.com/CDRH/open-oni_nebraska_theme), run `dev.sh` and then look at it, all is well.  Now, remove that theme from INSTALLED_APPS, rerun `dev.sh`, and you'll see that some of the CSS is still active.

I wrote a script to kill the `.static-media` directory, which worked great on Mac, but it does not work on Linux.

https://github.com/open-oni/open-oni/pull/236

If someone on Linux / Windows can attempt to replicate this issue, perhaps we can come up with a solution!  The solution might be "remove fingerprinted assets and re-collect them" but that seems like something that will be easy to forget to do.

**Comment by jechols** [comment]
Replicated the issue, tested, all seems well.  This probably needs a note in the theming guide, whenever we build it.  Anything overriding a static file (as opposed to just adding a new static file) will potentially break without running this clean script.
