### ISSUE TITLE
Consider destroying empty files in core

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#240]
`main.css` should probably go.  It just makes things confusing for people who are expecting this file to be defining some core rules.  Then we can fry the `__base.html` reference to that CSS, and make the default theme add it via block magic.  That gives us an example of using blocks to add a file, and cleans up core a small bit.

**Comment by srabun** [comment]
don't steer people to copying files that might change.

**Comment by jechols** [comment]
I think this lost its relevancy long ago, given that we don't have any empty *.css files anywhere today.
