### ISSUE TITLE
Search highlighting broken

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#246]
Search highlighting seems not to be completely working on the page view, though it is in the thumbnail view. 

For example, see below, with highlighted words. 

![screen shot 2016-07-29 at 9 23 11 am](https://cloud.githubusercontent.com/assets/284315/17251360/1755b474-556e-11e6-85fe-e84339dc475b.png)

When I click on the first result, only one of the words appears to be highlighted

![screen shot 2016-07-29 at 9 24 23 am](https://cloud.githubusercontent.com/assets/284315/17251398/3f734ee4-556e-11e6-9ae7-6b3f38795dc7.png)

I thought at first it was only the first word in the list being highlighted, but that does not seem to be the case. 

![screen shot 2016-07-29 at 9 25 32 am](https://cloud.githubusercontent.com/assets/284315/17251434/68ed4a18-556e-11e6-8fa8-f5d39854f705.png)

I first noticed this while testing @jduss4 's advanced search branch, but it exists in Master too, so it's not that branch.

**Comment by AndrewGearhart** [comment]
I'm not seeing this in my instance. Can anyone else confirm if this is happening to them?

**Comment by lindak716** [comment]
What aren't you seeing?

-------- Original message --------

**Comment by jechols** [comment]
I can replicate this problem in our instance now.  It appears the problem has to do with how the image highlights are created compared to how the Open Seadragon "overlays" work.  I expect to have a fix today.
