### ISSUE TITLE
Investigate test database

### ISSUE THREAD

**Issue by jduss4** [open-oni/open-oni#247]
I haven't had a chance to conduct more research into this, but I began to write tests for the context_processors and I realized that the results coming back were straight out of my development database, despite that I was loading fixtures (I thought).

We should look into how the test database is created and how to prevent this type of cross contamination from happening.

**Comment by jduss4** [comment]
Change all of the above from "database" to "solr" because that's the actual problem here

**Comment by jechols** [comment]
Oops - #248 is a dupe of this one.  I didn't see this....  Flip a coin and close the loser?
