### ISSUE TITLE
Split up solr config for test vs. production

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#248]
Django automatically handles test config for databases, but solr is out of its ORM magic domain, so our tests that hit the solr index are hitting the live one.  This makes tests very difficult and potentially risky if we have dev data we need kept safe.

I don't have a strategy for this, but it can't be /that/ hard now that we have a test_settings.py file.  Right?

**Comment by jduss4** [comment]
(I want to get updates so posting here)

**Comment by srabun** [comment]
investigate how images work in docker?

**Comment by jechols** [comment]
This can totally go away when we migrate to compose (which I plan to do before UO tries to get into dev on this again).  Having a test compose file which doesn't use data volumes, and running tests in their own "namespace" (via `docker-compose -p onitest` or similar), there would be no way for the test run's data to collide with dev data.  And doing this would mean we wouldn't have to hack up the app to support a test config for solr.

**Comment by AndrewGearhart** [comment]
PR coming soon (likely tomorrow) on a docker-compose that replaces dev.sh ...

**Comment by lindak716** [comment]
What is PR?

-------- Original message --------

**Comment by AndrewGearhart** [comment]
@lindak716 PR = Pull Request

**Comment by jechols** [comment]
With @AndrewGearhart's work and a small hack for a test-specific compose setup, I think we're good!
