### ISSUE TITLE
Augment load_batch error messages

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#253]
Error message change: specify not a bag structure

At minimum, document reason for error.

**Comment by techgique** [comment]
Added path checking here: https://github.com/open-oni/open-oni/pull/359/commits/dfbd19891b5412bf76e5ef3e2ed456d8ec207716

Could still add something to verify the bag structure

**Comment by techgique** [comment]
"Check checksum" - Karin in #254
:smile:

**Comment by karindalziel** [comment]
Added the documentation tag in here because it could potentially be addressed there. I think grant work on batch building and checking may address this.
