### ISSUE TITLE
Create migration to remove celery tables

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#258]
Otherwise we're going to have to tell people in our upgrade guide which tables to delete in MySQL.  The potential for catastrophic error is a little high for my tastes there.

**Comment by jechols** [comment]
Also: are there any other schema changes needed?  We should make sure nothing has changed that we're missing since we just nuke dev whenever we have problems.

**Comment by jechols** [comment]
We ended up just nuking the whole install, re-pulling our custom data (core_awardee, for instance), and reingesting all of our batches.  We found that to be less difficult than trying to figure out a good way to migrate data properly :(

That's a terrible thing to tell chronam users to have to do, though, so I really don't know the right solution.  Even if people keep their mysql data, I think you can't just reindex - you have to blow away all the solr data and then reindex, I think, since we're moving from such an antiquated version of solr.

This one probably needs more thought and discussion.

**Comment by jduss4** [comment]
I think it seems somewhat reasonable to ask people to reindex their stuff when moving to the software for the first time.  A lot of them will need to work on the site while their live chronam site is still up, so they could be ingesting batches behind the scenes for a few weeks.  But once somebody has openoni I think we should work on ways to migrate content without reindexing, for our own sanity as well :)

**Comment by jechols** [comment]
This is so obsolete now.  Closing.
