### ISSUE TITLE
Write a contributing.md file

### ISSUE THREAD

**Issue by AndrewGearhart** [open-oni/open-oni#260]
We should create a CONTRIBUTING.md file for contribution guidelines and instructions. 

Examples:
- https://github.com/thoughtbot/factory_girl_rails/blob/master/CONTRIBUTING.md
- https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md

**Comment by jduss4** [comment]
related to this:  https://github.com/open-oni/open-oni/wiki/Contribute
