### ISSUE TITLE
 Don't serve JSON coordinate files through django!

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#261]
Basically we want to grab https://github.com/uoregon-libraries/oregonnews/commit/835cd9183c06be83602043c5818d178664dcafc3 except without the stupid typos that @jechols dude made

**Comment by jechols** [comment]
s/typos/typo/

Ouch.

**Comment by jduss4** [comment]
@techgique want to work this into your docker compose stuff, since you might be moving the apache config stuff around?

**Comment by techgique** [comment]
This should probably be handled in 0.x `django-upgrade` before bigger docker changes for 1.x
