### ISSUE TITLE
Come up with some kind of strategy for editing incorrect issues and pages

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#267]
We often find ourselves having made a mistake in metadata entry.  In some cases, there's almost no chance of catching the error before we batch, just because it's so subtle - in one recent example, a 1908 paper had a smudge or something over the 8 that made it look just like a 3.

Our process for these kinds of things is generally purge the batch, rebuild the batch or fix the XML manually (depending on the problem, sometimes our automated rebuild is far easier), reingest.  But this can screw up our disaster recovery, because our dark archive is effectively a "write-only" datastore.  So we end up needing to either back up the differences or else hold a full backup of the new batch.

It would be really great if we could come up with some kind of standard "correction protocol" which the app could support.  Ideally, we could avoid reingesting, and store a new bag with just the corrections which the app would then load as if it were a "patch" or something.  Then for our dark archive, we'd just store this corrected bag.  We could throw away the original bad data if need be (say if it were a huge number of incorrect images), but the idea would be for small problems in the XML, we wouldn't need to bother with doing so.  And then, in the case of restoring from our dark archive, we wouldn't have to try and overlay batches on top of each other to deal with corrections; we'd just drop in all the files and tell the ingest process to load all the batches and then load all the patches.

Maybe this is a UO-specific concern, I'm not sure, but I definitely feel like we should have some kind of discussion in case others have better solutions (or just have ideas that could help).

**Comment by AndrewGearhart** [comment]
I think this is a valid idea. Just a thought.... Could it be handled with the batch versioning? batch_marcorg_batchname_ver## ?

If a new batch is loaded with a later version... it replaces the old batch?

Or... if it is a later version, could it replace as necessary any existing files?

I'm not sure if this would cause conflicts with the original purpose of the batch versioning scheme...

**Comment by jechols** [comment]
I don't know if you can load a batch that only contains, for instance, a handful of XML files.  That would certainly be a valid approach if the software supported it, though.  If not, I'm thinking something similar but with some kind of metadata file that tells ONI, "HEY YOU!  Don't load this as a batch, just patch an existing batch!"

**Comment by AndrewGearhart** [comment]
Having that type of metadata file would be a departure from the way ChronAm works though. I wonder if any of the developers at LC would have an opinion about having such a file or how they feel this type of activity should be accomplished. I agree though... that a patching method sounds very appropriate and desirable.

**Comment by jechols** [comment]
I thought our long-term goal was to diverge from the batch concept... at least that's something we've discussed in the past.  I know we were going to keep batches as an option for ingest, but that would just be a legacy thing.

UO wants a way to ingest a single issue, update OCR data, fix metadata like dates, etc. all from the web.  I don't know how that'll look, and it may be years before that happens, but UO's long-term goal is a far more "living" website rather than sticking with this "write once" approach.  If we can't get ONI to do these things, we'll probably end up building our own tools that sit next to ONI and handle these sorts of issues for us.  That would most likely be hard-coded for our needs in that case, so it's not ideal, but we can't keep spending time purging and reingesting when a small typo makes a 100-gig batch invalid.

**Comment by jduss4** [comment]
This is something UNL would be interested in too, I'm pretty sure.  @techgique added some scripts that he used to correct metadata which might be helpful to some of y'all.

https://github.com/open-oni/open-oni-scripts/tree/master/nebraska

**Comment by jechols** [comment]
What UO wants is something that lets us build a "diff" of sorts so the original batches aren't touched, and instead we have a "batch patch" that's relatively small (and rhymes!).  That way we aren't invalidating the dark archive (it's too much of a pain to properly purge and re-backup).

**Comment by jechols** [comment]
This is relevant to grant work, but we will start a new ticket for that since we have to figure it out from the ground up.
