### ISSUE TITLE
Applying logic to prevent empty searches

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#27]
http://nyshistoricnewspapers.org/#

check that search

**Comment by karindalziel** [comment]
Expand search to be dynamic

Select an option, others disappear - see #23

Default search does not come with counties, cities, state dropdowns

I think we may need to start simple witht his one, improving usability as we can, with an eye towards a UI overhaul later.

**Comment by jduss4** [comment]
I don't know if I like this, because it would make it much harder for users to just browse casually through things, or like, fly by the seat of their pants by using a city and a word, etc.

**Comment by raybrarian** [comment]
We will revisit - likely as part of ux/accessibility audit for Scoop.
