### ISSUE TITLE
Add a site-building django command

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#280]
At UO we're going to have a site that needs a \specific `settings_local.py`, `urls.py`, a theme, and probably two or three plugins.  This is going to be a pain for new devs, not to mention it's really kind of obnoxious to have to remember which things need to be downloaded, where, and how they're set up once we're ready for production.

I propose a new command that would read some kind of "site setup" file from any given URL.  This site setup file would have information on where to find the de-facto urls.py, settings_local.py (probably minus any sensitive information, if any exists), which plugins to pull from github, and which theme/themes to pull from github.

**Comment by AndrewGearhart** [comment]
Would be awesome if this ran off a yaml file (or could run off of a yaml file)... if so, it would be easy for the web container's startup to look for the yaml file and, if it exists, run on docker-compose up ... similar to the way that the database containers can have data automatically imported on startup.

**Comment by jechols** [comment]
The more I think about this, the less sense it makes.  Every solution to the problem is hacky, though....

**Comment by jechols** [comment]
@AndrewGearhart that actually makes a lot of sense for us, but there are still potential problems with that approach for us.  If I go and edit urls.py, and forget to fix the source urls.py file, I could lose whatever I'm trying to work on.  On the other side, if I want to change urls.py "the right way", I have to kill and restart the containers, which is rather slow for a quick fix.

Bleah.

**Comment by jechols** [comment]
UO handled this with a repo that just has some bash.  It's not pretty, but it works: https://github.com/uoregon-libraries/oni-wrapper

**Comment by jechols** [comment]
(Closed this because I don't see anybody having time to build something general-case - certainly not us)
