### ISSUE TITLE
update wiki entries regarding pre-release

### ISSUE THREAD

**Issue by AndrewGearhart** [open-oni/open-oni#281]
Since this milestone marks the leap past pre-release code, update the following wiki entries that refer to the pre-release code of Open ONI:

Candidates for Removal AFTER Being Replicated / Updated in `/docs` and `CONTRIBUTING.md`
- [x] [Configuration](https://github.com/open-oni/open-oni/wiki/Configuration)
- [x] [Contribute](https://github.com/open-oni/open-oni/wiki/Contribute)
- [x] [Development Standards](https://github.com/open-oni/open-oni/wiki/Development-Standards)
- [x] [Docker](https://github.com/open-oni/open-oni/wiki/Docker)
- [x] [Docker Examples](https://github.com/open-oni/open-oni/wiki/Docker-Examples)
- [x] [Installation](https://github.com/open-oni/open-oni/wiki/Installation)
- [x] [Plugins](https://github.com/open-oni/open-oni/wiki/Plugins)
- [x] [Theming](https://github.com/open-oni/open-oni/wiki/Theming)

Candidates for Removal
- [x] [Getting Started](https://github.com/open-oni/open-oni/wiki/Getting-Started)
- [x]  [Open ONI Versions](https://github.com/open-oni/open-oni/wiki/Open-ONI-Versions)
- [x] [Using Open ONI](https://github.com/open-oni/open-oni/wiki/Using-Open-ONI) (I think this can be merged into the About page or Home, etc ?

**Comment by jduss4** [comment]
what the I can click that checkbox and it says "edited by jduss4" at the top of your post now, haha.  I didn't know github had checkboxes like that!

**Comment by techgique** [comment]
I think we're going to want to move docs into the repository itself for 1.x.

Jeremy had suggested using `git describe` with a git hook to generate a descriptive `VERSION.md` upon updates to master too. Then we might not need a separate page in the docs.

**Comment by techgique** [comment]
The above wiki page can probably be dropped as the changelog file itself specifies we use Semantic Versioning. @jduss4 could you take a look in your documentation work?

**Comment by jduss4** [comment]
Agreed, I marked that one as "remove" in my notes when I surveyed the wiki articles. It seems like our changelog can take care of itself, there!

I will use this issue to track some of the wiki pages that may need updating or removal after the documentation overhaul, however.

**Comment by techgique** [comment]
I had a note written somewhere about moving the "About Open ONI" page into github.io pages. Seems like the most comprehensive "about" page should be on the website rather than in the wiki. I believe the Readme and some other places link to that wiki page, so we'd need to be careful to update all of them.

What do you think?

**Comment by jduss4** [comment]
I had actually had a similar thought, but then I didn't pursue it because I didn't know how far that might lead, but I would be into putting that on the website.  It would be more visible there, for one thing!

**Comment by techgique** [comment]
I think Open ONI versions can be dropped. "Using Open ONI" can probably be incorporated into existing docs. I think the only parts really unique to it are talking about whether people should fork or not if they want to use it. What do y'all think?

That would leave as the only things in the wiki:
- Sites Using Open ONI
- Resource Usage
- Create Your Own Batch

Does that look/sound right?

**Comment by jduss4** [comment]
They are gone!
