### ISSUE TITLE
Figure out a better solr config

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#289]
Right now we've got solr 6, which has a slick managed schema option, but due to time constraints we're defining every single field individually.  It may take some work (and probably reindexing for us at UO), but it would be really nice to rename all the fields in the code so they make use of the managed schema magic.  As much as possible, I'd like to have us not telling Solr how we want things indexed, and instead use the conventions.

One area this fails a bit is the language-specific OCR.  ONI uses language prefixes like "spa" and "ger" where Solr would use "es" and "de".  If possible we should make some kind of lookup so the OCR fields don't need a per-language definition, and instead the app says, "Oh, this is 'spa'; that means I should index it in 'ocr_es'"

**Comment by jduss4** [comment]
As a first step towards this, I have recreated our current schema via the schema API, but have not attempted to rename or redefine fields to use all dynamic definitions, etc.

**Comment by jduss4** [comment]
See #446

**Comment by jechols** [comment]
This ticket may be one worth closing - with PR #451, we're no longer overriding the entire configuration.  We now simply tell solr about the ONI-specific schema bits and call it a day.  I believe this gives us the benefit of not having to manage the entire `schema.xml` file, but without the pain of trying to change every single piece of the application that touches Solr.
