### ISSUE TITLE
Let's save space on word coordinates!

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#314]
We're finding that on our production server, we have something like 35 gigs of word coordinates and 30 gigs of mysql data in the core_languagetext table.

I'm fairly certain the XML files contain everything the word coordinate files contain (and more).  I think we should consider ditching the word coordinate files entirely and change the highlight logic to parse the data in the XML, since we know that in all cases that XML file has to exist for word highlights to exist.

It's also probably worth figuring out if core_languagetext can just be dropped.  Solr's data is what we should use for searching, and the XML is what we should use for exposing information to the browser.

---

It may make sense to rethink this if we can implement OCR corrections, but in that case I think we need to look at putting word coordinates into solr and presenting the highlight data on demand rather than from a static file.

**Comment by jechols** [comment]
(FYI, the reason this is important is for staging and development setups.  Production obviously has a ton of space because it has to have the batches available, but staging and dev should use as little disk as possible while still being able to ingest a good amount of useful data)

**Comment by johnscancella** [comment]
@jechols we recently removed the language text table for the same reason. If you want to look at how we did it check out https://github.com/LibraryOfCongress/chronam/pull/159

**Comment by jechols** [comment]
Nice though this would be, clearly it's not a high priority even for us at UO. Closing.
