### ISSUE TITLE
Update solr to latest 4.x

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#33]
Test.

**Comment by jduss4** [comment]
The docker setup is using solr 4.10, which is the final of the 4.x versions.  The latest solr is 5.4.0 but the migration won't be trivial:
https://cwiki.apache.org/confluence/display/solr/Upgrading+a+Solr+4.x+Cluster+to+Solr+5.0
https://cwiki.apache.org/confluence/display/solr/Moving+to+the+New+solr.xml+Format

General guide
https://cwiki.apache.org/confluence/display/solr/Upgrading+Solr

**Comment by karindalziel** [comment]
Not going to include this for the January 2016 codesprint because we don't have experience with Solr 5 yet. Others are free to pick up.

**Comment by karindalziel** [comment]
4.10 is the latest release 4.x, will start another issue for 5.
