### ISSUE TITLE
expose solr admin UI in development docker

### ISSUE THREAD

**Issue by jduss4** [open-oni/open-oni#332]
this would be helpful for debugging purposes to browse the content, test out queries, etc

**Comment by jechols** [comment]
FYI, not sure if this should stay open.  If you want to do this, it can be done pretty easily via a `docker-compose.override.yml` entry like this:

```yaml
  solr:
    ports:
      - 8983:8983
```

This was deliberately removed from the core dockerfile because it made it painful to stand up multiple apps which forcibly expose things like solr

**Comment by jduss4** [comment]
We should add that to the documentation for the docker-illiterate like me, who would need to sit down and read / think a bit before seeing how to map the port. If it's in the docs, then let's close this!

**Comment by jechols** [comment]
We could toss it into the override file, since we tell devs to copy that and modify as necessary: https://github.com/open-oni/open-oni/wiki/Docker.  I'm not sure if that's well-documented enough, given it's in a wiki page people may or may not actually read....

**Comment by jechols** [comment]
Oh, heh - we already have an example.  Looks like I added that previously.  We could add examples for all the services, though, if you think that would help.

https://github.com/open-oni/open-oni/blob/master/docker-compose.override.yml-example#L12-L16

**Comment by jduss4** [comment]
I think that would be helpful, yeah!

**Comment by jechols** [comment]
Closing this - the new ticket should cover it!
