### ISSUE TITLE
Bad characters in bootstrap breadcrumbs

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#335]
![screen shot 2018-08-17 at 11 33 07 am](https://user-images.githubusercontent.com/284315/44277804-78d26c00-a211-11e8-8c49-fb3e666d1677.png)

**Comment by jduss4** [comment]
it's so bad that the image demo is crying for help

**Comment by jduss4** [comment]
@karindalziel says this was nebraska specific and has since been resolved
