### ISSUE TITLE
Separate out batch location 

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#35]
With backwards compatibility!

Review settings file.

**Comment by jduss4** [comment]
Presumably you would change these lines of the settings:

```
STORAGE = '/opt/openoni/data/'
BATCH_STORAGE = os.path.join(STORAGE, "batches")
```

Or you could just hardcode in "BATCH_STORAGE" to whatever you needed.  Not sure about the backwards compatibility part, though, I think your batches would need to be one place or another, not split among many places unless if we start getting really fancy.  Closing issue for now.
