### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by jduss4** [open-oni/open-oni#365]
As we work towards adding more contributors / collaborators / users of the software, we should also work on a code of conduct for the community.

@AndrewGearhart recommends looking into  https://www.recurse.com/code-of-conduct
@karindalziel recommends looking into  https://www.contributor-covenant.org/

Do other folks have any codes they like that we should look into?

@AndrewGearhart has also pointed out that GitHub recognizes CoC files, so we can use that system when we adopt something:  https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

**Comment by techgique** [comment]
See also #356

**Comment by jduss4** [comment]
Oh crumbs, sorry for the duplicate issue.  Which one do we want to keep?

**Comment by techgique** [comment]
Probably this one because it has more links to resources

**Comment by techgique** [comment]
Our code of conduct will be based on Django's: https://www.djangoproject.com/conduct/

We will adapt their code of conduct for our smaller community where we don't have enough active participants to form a board and committees yet and Slack is used as our primary platform for communication.

**Comment by jduss4** [comment]
I assume this is going to be a file in the repository rather than in the wiki or something, but we may want to add links from the project's website and the contribute / community type pages in the wiki to the CoC as well during our revamp

**Comment by techgique** [comment]
I was assuming the CoC would be a document at the root of the project files. It seems like a priority number one kind of document. I could also see it being just inside `docs/`, but am leaning towards the former option.

**Comment by jduss4** [comment]
Agreed, I was picturing `/CODEOFCONDUCT.md` or something to that effect
