### ISSUE TITLE
Add Agent/Partner Metadata and Display

### ISSUE THREAD

**Issue by kestlund** [open-oni/open-oni#38]

**Comment by karindalziel** [comment]
https://github.com/open-oni/open-oni/issues/39

**Comment by jduss4** [comment]
Can we get more information about this one?  I'm not sure I understand what agents / partners are in the context of pages.

**Comment by jechols** [comment]
Is this related to our current super-magic "awardee" metadata?  i.e., the "Image provided by x" tag on images?
