### ISSUE TITLE
Investigate use of fragment identifiers in search result URLs

### ISSUE THREAD

**Issue by techgique** [open-oni/open-oni#392]
While working on [cleaning up search result URLs](https://github.com/open-oni/open-oni/pull/389/commits/49c7ef8abda36cdb708273b12346f8a89b3b5695) and trying to return URLs with the words as a query string parameter rather than a fragment identifier, I learned that the app will return a redirect to requests for pages with a query string parameter: https://github.com/open-oni/open-oni/blob/49c7ef8abda36cdb708273b12346f8a89b3b5695/core/views/browse.py#L175

I understand that it's due to the way the JavaScript is written to handle the highlighted words in the UI, but am curious about any other side effects of this approach including but not limited to the URLs that look weird in search results (e.g. `https://…/lccn/sn99021999/1887-03-07/ed-1/seq-1/#words=name+named+namely+names`)

I'm inclined to say this should be handled through a `data-words="…"` HTML attribute rather than fragment identifiers in the URL.

This may affect search engine results. There is other code related to redirecting requests that are suspected to be links from search engines in `browse.py` too.

**Comment by jechols** [comment]
Using fragments is a pretty common approach for this sort of thing so that you can do things like a redirect or share a link with highlights. I move to close this issue.
