### ISSUE TITLE
Clipping Quality

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#408]
When an issue is "clipped" the quality seems significantly lower than in chronam. Also, if one clips the image when the entire page does not fill the viewport the page gets stretched. This is also present on chronam.

I am hoping this may get fixed with more IIIF integration, so this is pretty low priority. 

![Screen Shot 2019-09-10 at 2 44 27 PM](https://user-images.githubusercontent.com/284315/64646152-14fe8080-d3dc-11e9-819f-044e4036d49d.png)

**Comment by techgique** [comment]
Noticed that this is causing RAIS warnings in the syslog.

Going to: https://nebnewspapers.unl.edu/lccn/sn96080312/1987-09-23/ed-1/seq-1/print/image_537x817_from_33,3591_to_4754,10772/

Results in:
```
Sep 11 11:42:01 nebnews-prod journal: 2019/09/11 16:42:01.093 - rais-server - WARN - FROM OPJ: Right position of the decoded area (region_x1=4754) is outside the image area (Xsiz=4714).
Sep 11 11:42:01 nebnews-prod journal: 2019/09/11 16:42:01.093 - rais-server - WARN - FROM OPJ: Bottom position of the decoded area (region_y1=10772) is outside the image area (Ysiz=7182).
```

**Comment by karindalziel** [comment]
I can't reproduce the stretching anymore. The quality of the full page is still not great, but people are never going to be able to read the content when the full page is clipped so I move that we close this. 

I would love to research a new clipping mechanism where the user could draw a box and produce a clip, probably through a IIIF viewer.
