### ISSUE TITLE
Review robots.txt

### ISSUE THREAD

**Issue by techgique** [open-oni/open-oni#409]
We are seeing a less well-known bot crawl our website and request full-size images at URLs like `/lccn/sn99021999/1887-03-27/ed-1/seq-8.jp2` but then bailing on the connections before the web server finishes the transfer. It drew our attention to our `robots.txt` file.

@karindalziel suggested we limit them further to only allow browse pages and URLs with OCR.

We probably also want to add an XML sitemap.

This is our `dev` branch `robots.txt`: https://github.com/open-oni/open-oni/blob/dev/static/robots.txt

**Comment by jechols** [comment]
May make sense to have an example robots.txt that works OOTB, but I think we should take the one that's there out so people know they can (and probably should) customize it.  It's just too hard to come up with rules that everybody is going to want.  I think we're totally okay with JP2s being spidered on our end, for instance.

A sitemap would be a very valuable thing, but that should have its own ticket - it's a big task.

**Comment by techgique** [comment]
Hmmm. If we take it out, is there somewhere we can loudly communicate to people that they are missing a robots.txt? I think denying everything is a safer bet out of the box with some commented examples of how to allow / block common things in comments is a good starting point. Maybe we put a file like that in the default template and mention it prominently in the theme documentation?

A separate ticket for a sitemap is a good idea. It definitely will be a bigger task.

**Comment by jechols** [comment]
I still see this as something that's the responsibility of the person setting it up.  We should document it wherever we have production setup information (which right now is admittedly pretty sparse), and perhaps provide examples, but I don't buy that denying everything is a safe bet.

We (UO) get a great deal of traffic from web searches, and want to err on the side of allowing more, not less, spidering.  In the past ten years have had only one time spidering caused us problems, despite having hundreds of thousands of pages and a very modest server running our site (if you don't consider the cost of disk, our entire stack could run on a single $40/month Amazon EC2 instance).  Sites with less content than us should have no difficulty with even extremely heavy spidering.  (For reference, our robots.txt is vanilla: https://oregonnews.uoregon.edu/robots.txt)

Which is all a long way of saying I don't believe there is a need to worry about this beyond documenting it.
