### ISSUE TITLE
Don't accept titles when MARC is missing data!!!!!!1!!111!one!11!

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#411]
This caused a *massive* amount of wasted time.  Like ... several days lost.

Problem: we had a marc record that had no location info (the "752 tag", if that's how you refer to it).  The rest of the MARC seemed fine.  ONI loaded the title and dropped data into a bunch of tables.  Something after the title load totally puked when indexing something in solr.  There was no obvious correlation between the two events, so I was debugging all kinds of completely unrelated stuff.

Eventually I figured out the root cause.  I deleted the title from the database (a non-trivial process due to all the related data), then hacked up and loaded new XML.  As far as I can tell, it's working.

If ONI cannot function without a piece of data, it shouldn't succeed in loading that data.  I propose that the title loader verifies things it requires before doing *anything* in the database.

**Comment by jechols** [comment]
If this is tackled, it should be with an allowance for adding titles some other way.  See my comment on #28

**Comment by techgique** [comment]
I'm imagining that augmenting the existing batch and issue loading to block if that field is missing is the quickest "fix" here. Preventing the mess that you had to sort out seems like a blocker for 1.0 release to me, especially as you mention it's common for periodicals to not have that MARC field.

**Comment by jechols** [comment]
See #414: I think fixing that one fixes this one.

**Comment by jechols** [comment]
This should be fixed now that failed title loads cause issues not to load.  Verification should happen, though, so I'm leaving this open until I am certain, as this was a big problem.

**Comment by jechols** [comment]
Having a hell of a time trying to reproduce this bug again.  On master, things run smoothly when I forcibly bypass the block that processes the 752 data.  On the dev branch I get the same result.  Which means I need to test against v0.10.0, which is a major pain to get set up - it's a lot more work than 0.11, it seems....

**Comment by jechols** [comment]
Okay, looks like simply skipping the 752 code isn't enough to trigger this problem - you actually have to remove those fields from a MARC record.  Not sure why, and no time to really care about it.

Replicated the problem on v0.10.0 and v0.11.1.  Testing dev now.

**Comment by jechols** [comment]
This is still a bug on the `dev` branch.  The fix in #414 doesn't stop bad title data from getting stored.  The bug reported there related to titles *failing* to load, and that was indeed fixed.  But in this situation, the MARC data is incomplete, but the title loader isn't throwing an exception, so the title still gets into the database in a state that prevent the app from working.

**Comment by jechols** [comment]
PR #431 fixes this by preventing bad data from getting into the database, but there's still no way to load titles manually.  I think that #431 is worth merging ASAP, however, because cleaning up bad data from an aborted title load is a massive pain.
