### ISSUE TITLE
Clean up unused branches from chronam fork

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#42]
Forgot to get this on there at the meeting. Maybe we can just say anything not touched in a year can be deleted, and we take the rest on a case by case basis? Thoughts?

**Comment by jechols** [comment]
It may be best to just destroy anything we aren't actively using.  It's easy enough to pull a branch from upstream if we decide we want it later.  And we're likely to have to deal with painful merging whether we hold onto the branches or throw them away and re-pull them later.

**Comment by karindalziel** [comment]
I'm leaning towards just delete all the old branches, but am open to other ideas.
