### ISSUE TITLE
Clean up wiki and create studs for new organization

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#43]
We may end up using readme's exclusively for documentation, but I'd like a clean wiki in any case.

**Comment by lindak716** [comment]
I'd be happy to help to clean up the wiki. Can we have discussion to plan?

**Comment by karindalziel** [comment]
@lindak716 sure! Are you in the slack room? Or would you like a phone call?

**Comment by jduss4** [comment]
I'm going to take a quick stab at this, @karindalziel , while a batch is loading!  :)
