### ISSUE TITLE
Handle lockfiles at a deployment level rather than ONI

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#447]
### Problem

If we specify dependencies in a lockfile, adopters can't update things like getting a minor point release of django very safely.  Here's an example that could legitimately happen at UO:

- ONI specifies django 2.2.X in the lockfile (`requirements.lock`)
- Django 2.2.Y comes out, fixing a critical vulnerability
- ONI updates to Django 2.2.Y quickly, perhaps, but UO doesn't follow every ONI release
  - UO doesn't want to deploy the whole stack to get a critical Django update (just like we wouldn't want to grab a new version of Hyrax to get a critical Rails update)
  - (Really, we don't - we pin to a specific release and test it thoroughly, even if the next release *appears* to have very little change)
- UO updates django to 2.2.Y locally
- Some time passes, and UO needs to do a redeploy of our ONI site, but still don't have time to do a thorough update process, so we just run the automated deployment procedure
- Auto-deploy pulls down the pinned ONI release, overwriting `requirements.lock`.  We roll back to a broken Django and don't even realize it.

Other possible scenarios I can see:

- Somebody has a plugin which adds a requirement to their stack, and they want to freeze their local app's requirements, not be pinned to ONI's smaller requirements list.  If they do this, next time they deploy ONI they lose their `requirements.lock`

### Solutions?

- We ditch `requirements.lock` and git-ignore it - this seems to be what Hyrax has done
  - Need a way to still ensure core contributors are on a consistent setup
  - Need to specify all our dependencies' versions more carefully - right now we claim that ONI needs, for example, "pymarc".  Will literally *any* version work?  I doubt it....
- We document that `requirements.lock` is for ONI core and that adopters should have their own lockfile if they want to update local dependencies
  - Need to spell out what this means, how they do it, and why it's important to keep track of things locally

Others?

**Comment by techgique** [comment]
This is still a challenge if adopters deploy with extra Python packages. #534 and [updated production documentation](https://github.com/open-oni/open-oni/blob/dev/docs/install/centos/openoni.md#python-dependencies) don't accommodate this. I suppose for Docker Compose, deployers could overwrite `requirements.lock` with another file, but if our dependencies change and they pull it might still break their deployment. I don't think we can really take on support for such custom deployments though.

The first proposed solution wouldn't work now that we're always installing from a stable `requirements.lock`. And our `requirements.pip` still accommodates what we expect at this time to be safe updates. Testing will of course always be necessary when we update `requirements.lock` this way. We'd lose one of these components if we went the road of git-ignoring `requirements.lock`. So I'm leaning towards the second solution where we try to encourage adopters to use a separate custom lock file. :thinking:

**Comment by jechols** [comment]
Yeah.  I don't know the right answer here.  I think it's something we may never solve, and just have to do our best to ensure people are aware.
