### ISSUE TITLE
consider building "on this day," "random" type retrieval into core

### ISSUE THREAD

**Issue by jduss4** [open-oni/open-oni#467]
See discussion on featured plugin:  https://github.com/open-oni/plugin_featured_content/issues/14

I like the idea of providing some very basic functionality like, "get X front pages from this day in time" or "get X random front pages" in core, and then the featured_pages plugin, if it continued to exist, would simply be "read pages from this JSON file" rather than trying to do it all, so to speak.

**Comment by karindalziel** [comment]
moving this to "wishlist" for now. could move to community discussion
