### ISSUE TITLE
Fix reindexer

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#474]
During an ingest, non-OCRed pages don't get indexed.  The reindexer, however, isn't so picky, which causes the app to crash in the middle of a reindex.  We should use similar logic to avoid indexing page records that have no OCR.

See https://github.com/open-oni/open-oni/blob/dev/core/batch_loader.py#L403

**Comment by techgique** [comment]
Looks like this _might_ be a simple fix. Do you think a related test will be of any use once the code is fixed? Or perhaps this kind of page should be in one of our sample batches we use for testing ingest etc?

**Comment by jechols** [comment]
I think a test might be a good idea.

Here's the fix I used locally:

```patch
diff --git a/core/solr_index.py b/core/solr_index.py
index 6928e77..a946083 100644
--- a/core/solr_index.py
+++ b/core/solr_index.py
@@ -578,7 +578,7 @@ def index_pages():
     solr = SolrConnection(settings.SOLR)
     solr.delete_query('type:page')
     cursor = connection.cursor()
-    cursor.execute("SELECT id FROM core_page")
+    cursor.execute("SELECT id FROM core_page WHERE ocr_filename IS NOT NULL")
     count = 0
     while True:
         row = cursor.fetchone()
```

**Comment by jechols** [comment]
If we want any kind of resumable indexer, it'll need more effort, and at the moment I'm not sure how to do that.  I'm thinking I'll manually flip all the pages' `indexed` fields to false and hack in a check for that.  If it works out, we could add a flag to the task for index options - but that complicates things.  The index task actually runs two subtasks (title and page reindex), so the page reindex would need to also have said flag.

Anyway, my thoughts on this flag: `--all` sets all pages' `indexed` fields to false and then kicks off the reindex.  `--resume` runs the indexer, but doesn't flip that field.  Then the core indexing code adds `AND indexed <> 0` to the `WHERE` clause.

If you don't specify a flag, it is a hard failure so people know they have to specify `--all` or `--resume`.

**Comment by jechols** [comment]
FYI, `page.indexed` appears to literally be a write-only field today.  It's set to True when batches are ingested, but I don't see it being read anywhere.

**Comment by jechols** [comment]
Note that implementing something like this resumable stuff should probably be its own ticket.  Just jotting things down here as I go so I don't forget.  Also note that using `page.indexed` in the way described here would likely mean a lot of other considerations.  For instance, `zap_index` would need to update all pages' `indexed` fields in the database.  There may be other stuff to consider.

**Comment by jechols** [comment]
Ignore all "resume" conversation here.  See #475 for that mini-project.

**Comment by jechols** [comment]
Note: the current page index code (`core/solr_index.py`) starts by **deleting** all pages from the Solr index.  This seems wholly unnecessary - I'm not seeing anything bad happen if docs are already in Solr when the reindex starts.  If my test on our staging server goes well, I'm thinking we just remove that from the reindex operation.

**Comment by AndrewGearhart** [comment]
As discussed in Slack. As we consider the API structure, we should _probably_ outline with Open API spec (ie Swagger).
