### ISSUE TITLE
Example settings doesn't actually work if the site is running on a nonstandard port

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#495]
e.g., if you set the app up such that `ONI_BASE_URL` is `http://192.168.56.130:8080`, the app will fail to populate the `ALLOWED_HOSTS` array properly.  Why?  Because some knucklehead named @jechols doesn't know how to use Python properly!

- `url.netloc` is the URL's "Network location part".  Okay, that's meaningless, but a quick check reveals that it returns `192.168.56.130:8080` in this example.
- `url.hostname` is ... the host name.  Which is what you're supposed to put into `ALLOWED_HOSTS`.  So this kind of should have been the obvious go-to.

The fix is simple.  I just needed to rant at myself for a bit.

**Comment by jechols** [comment]
I didn't spell out the fix, but it really *is* simple: we just need to use `url.hostname` in the example settings, rather than `url.netloc`.

**Comment by techgique** [comment]
Thanks for the clear explanation! Good to know
