### ISSUE TITLE
Port code from our standalone installs

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#5]
- https://github.com/uoregon-libraries/oregonnews
- https://github.com/CDRH/nebnews
- Any others?

**Comment by karindalziel** [comment]
Not changing the milestone, but this is something non tech people could handle if they want.

**Comment by jduss4** [comment]
I think that Nebraska has gotten the majority of our code ported in, from bug fixes to features like cities in the search bar.  The plugins give us the only other features that we needed to bring with us.

**Comment by jduss4** [comment]
I am closing this issue because I feel that in general, code that needs to be added has been made into issues.
