### ISSUE TITLE
fix paths on PR template

### ISSUE THREAD

**Issue by AndrewGearhart** [open-oni/open-oni#510]
Paths for contributing.md are incorrect in the 
Pull Request template - 
`.github/pull_request_template.md`

On Lines 24 & 27 ... link is:
/CONTRIBUTING.md#...
Should be:
/open-oni/open-oni/blob/dev/CONTRIBUTING.md#...

**Comment by gabbyprecious** [comment]
Hello, Is anyone working on this, can I get assigned and will like to jump in on it.

**Comment by techgique** [comment]
Hi @gabbyprecious. I've assigned you to the issue. Please fork the repo and submit a PR, and we'll go from there. Thanks!

**Comment by techgique** [comment]
Haven't seen a PR from @gabbyprecious yet, so I'm just going to do this on a branch with other documentation updates.
