### ISSUE TITLE
solrpy 1.0.0 causes errors on setup.

### ISSUE THREAD

**Issue by AndrewGearhart** [open-oni/open-oni#520]
During setup, solrpy 1.0.0 fails to properly setup.
Version pin solrpy to 0.9.9 in requirements.pip until https://github.com/search5/solrpy/issues/55 is resolved.

**Comment by techgique** [comment]
D'oh. More upstream things breaking our software. Thanks for making an issue here and proposing a fix for upstream :raised_hands:

**Comment by jechols** [comment]
Closing this given #560
