### ISSUE TITLE
Waffle Guide (Navigating Issues w/ Waffle.io)

### ISSUE THREAD

**Issue by AndrewGearhart** [open-oni/open-oni#53]
Backlog*​ (leaving some stuff here till dependencies are done) 
​*Questions*​ (for anything people have a question on)
​*Ready*​ (Most stuff is here, but I have not prioritized)
​*In Progress*​ (Move issues you are working on here. You can also do this automatically using https://github.com/waffleio/waffle.io/wiki/Recommended-Workflow-Using-Pull-Requests-&-Automatic-Work-Tracking)
​*Check*​ (Move things here if you'd like someone to check it)
​*Done*​ (Move things here when done)

**Comment by karindalziel** [comment]
Just use github issues
