### ISSUE TITLE
Install python dependencies *always*

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#568]
When the docker environment starts up, we only run the pip update operation if `ENV/lib` doesn't exist: https://github.com/open-oni/open-oni/blob/dev/docker/_startup_lib.sh#L13-L16

This is not a good idea.  It probably saves us a few seconds on startup, but it causes us to have to blow away `ENV` every time something in our requirements changes, which slows things down a great deal in those cases.  It also wastes time trying to debug why a given library claims not to be present when we know we just added it to the requirements.

I believe it is likely we could just blindly run the pip install without any trouble.

**Comment by jechols** [comment]
It might make sense to not run the entire `/pip_install.sh` script, since that does a lot more, so maybe if `ENV` exists, we just run `pip install -U -r requirements.pip`, and if there is no ENV, we run the whole script, which installs and updates pip, etc.

**Comment by jechols** [comment]
I'm not actually even sure that `/pip_install.sh` is a good idea on the whole.

- pip, setuptools, and virtualenv should all already be installed in the docker image.  They should never have to be installed.
- Creating the `ENV` dir via virtualenv should only happen if it's not already there
- The pip install for dev and testing should really use the lockfile for consistency, not generate a new one
- If we create `ENV` outside the ONI directory, and change everything to source from that location's `bin/activate`, we won't have to end up with a local `ENV` that lives outside the docker image.

I think we have a PR or tickets for some of this already.

**Comment by techgique** [comment]
I like the thoughts on pip etc being handled in the Docker image unless we learn from other Python devs that it is still wise to update those beyond what Ubuntu provides. I could see that potentially being better in terms of how it resolves dependencies etc for what comes out in `requirements.lock` for when we choose to update that. BUT, I think that is scope creep for this issue.

I think for now, we should just go ahead and run `pip install requirements.lock` every time the web container starts. Doing the command you mentioned above with updating the dependencies is going to give everyone different environments which is what we're trying to avoid, so I think we want `requirements.lock`, yes?
