### ISSUE TITLE
Avoid merge conflicts in changelog

### ISSUE THREAD

**Issue by techgique** [open-oni/open-oni#569]
## Problem
We're seeing merge conflicts gunk up our workflow while we have more than one PR in the works at a time due to changelog edits. We had seen this problem after adding the changelog, but it's become much more annoying now that we aren't as quick to review and merge each PR before another feature branch is started.

## Research
I did some searching and found a couple pages suggesting adjustments that I think we could adapt for our workflow, listing them in chronological order (this problem has been around a long time):
- https://web.archive.org/web/20190412170433/http://krlmlr.github.io:80/using-gitattributes-to-avoid-merge-conflicts/
- https://tgstation13.org/wiki/Guide_to_Changelogs
- https://about.gitlab.com/blog/2018/07/03/solving-gitlabs-changelog-conflict-crisis/
- http://seanwallis.com/post/resolving-changelog-merge-conflict-madness/
- Also, I saw a few people suggest adding a few "placeholder" lines in each section to be filled as needed, but that seems like a poor solution where merge conflicts are still going to happen as people have to coordinate not placing messages on the same placeholder lines. No thanks.

### Thoughts
The union merging approach still requires manual cleanup at the end and also seems like it will lose track of the order of the changes if the order of lines is indeed random in the end. I think multi-line changelog additions in a PR would make this messier too, even if we followed the hint to always add edits at the top of a section. I'd like to keep some sense of chronology in the final changelog from top to bottom. Though I don't think it needs to be exact, otherwise that would be a hassle for the proposal I have in mind for below.

Using separate files in a `changelogs/` directory is a robust way to avoid merge conflicts from an arbitrary amount of contributors before a release.

I'm not keen on the idea of asking people to write changelog entries in a more specific format than the Markdown standard we're using to facilitate fully automated combination at release time. I don't want to add any more friction to community contributions and it could be error-prone. I think we can handle this in a way to make the work relatively modest at release time.

_Maybe_ automation could be explored down the road, but for now I'd like to just get a quicker manual approach in place to end the changelog merge conflicts ASAP. Combining things on a release branch is less of a hassle than the merge conflicts are in terms of back and forth between submitter and reviewers.

## Proposal
After each release, we add a `changelogs/` directory on the `dev` branch and include a template file `YYYY-MM-DD-username.md` that includes the section headers of the Keep a Changelog format we follow. We request that each PR include a file in the `changelogs/` directory named with this pattern `YYYY-MM-DD-username[-#].md`. The date will be the day the PR is submitted, and numbers at the end are used if one submits multiple PRs in a day to avoid merge conflicts with one's own other PR(s). 

At release time, a project maintainer will manually add these to the main `CHANGELOG.md` file and delete the `changelogs/` directory on a release branch. Another option would be to just delete everything but the template file. Then there wouldn't be an extra commit on the `dev` branch after each release, _but_ it would leave the directory and file that are kind of useless in the release. I think I'd rather have the extra commit than the cruft in the released files though.

Hotfix branches off of `main` would directly edit `CHANGELOG.md` and bypass the `changelogs/` directory.

**Comment by techgique** [comment]
Another edge case concern with `.gitattributes` approach is if Migration notes were dependent on order. Though I suppose in those rare circumstances it could be resolved in a commit directly on `dev` right after a PR was merged if the union merge mixed things up. Or in a release branch.

**Comment by jechols** [comment]
I haven't read through all the docs you linked, but I've skimmed everything.  I don't love `.gitattributes`.  I see the potential for confusion that could slip since there would be no manual reconciliation unless we remembered to triple-check prior to release.  I don't love `changelogs/*`, but it does solve the problem.  I don't know that I care about automated tooling like what gitlab describes, but that's something maybe worth investigating.

**Comment by jechols** [comment]
To be clear: I support your proposal generally, though automated tooling might be worth looking at as it might help.

**Comment by techgique** [comment]
Yep. Automated tooling could save time, but I think that'd be a phase 2 element of this. If we went with the `changelogs/` approach, my hope is that the standard filenames would make it easier to automate things into the right order than having to use git-based tools to examine commits. Even then, I still suspect we'll want an element of final review before a release regardless of how we approach this. Unless we really start pumping out releases like crazy, I hope that won't be a problem.
