### ISSUE TITLE
Images not showing (even with correct file permissions)

### ISSUE THREAD

**Issue by michaelmherrera** [open-oni/open-oni#579]
Hi,

I'm a student at Stanford and am hoping to use Open ONI as a volunteer project to help a high school newspaper digitize their archives. Thanks for this amazing piece of open source software!

I went through the process of install open oni via docker compose and loading one of the sampled batches. However, the images do not display (see below). I've verified that they are accessible, because I can download them when I browse to a specific issue.

I know that this could be caused by a permissions issue, but my permissions seem to be correct. I used `sudo docker-compose exec web bash` to enter into the container and verified the permissions. Here's an example of the permission for a given issue:
```
root@2ea2be4147ac:/opt/openoni/data/batches/batch_nbu_manyissues_ver01/data/sn99021999/0020653817A# ls -l 1887030301
total 7908
-rwxrwxr-x 1 1000 1000 5006338 Apr  2 17:41 0003.jp2
-rwxrwxr-x 1 1000 1000 1249341 Apr  2 17:41 0003.pdf
-rwxrwxr-x 1 1000 1000 1772973 Apr  2 17:41 0003.xml
-rwxrwxr-x 1 1000 1000    4801 Apr  2 17:41 1887030301.xml
-rwxrwxr-x 1 1000 1000   49892 Apr  2 17:41 1887030301_1.xml
```

I would appreciate pointers on what I'm doing wrong. Thanks for all your help!

![image](https://user-images.githubusercontent.com/52046844/113440444-49140a80-93a1-11eb-9ea7-4daddee7a584.png)
![image](https://user-images.githubusercontent.com/52046844/113440789-f1c26a00-93a1-11eb-9f05-31a7616a16b3.png)

**Comment by michaelmherrera** [comment]
Oh, and I forget to mention that I checked the logs and didn't notice anything out of sorts. I've attached them below, for reference
[open_opi.log](https://github.com/open-oni/open-oni/files/6250773/open_opi.log)

**Comment by jechols** [comment]
After discussion it turns out this is due to a problem we fixed, but never put into a release.  Working on a hotfix (v1.0.6) now.

**Comment by techgique** [comment]
RAIS on `main` branch fixed now
