### ISSUE TITLE
Research: Django best practices for developing an API that could incur heavy disk i/o or CPU impacts

### ISSUE THREAD

**Issue by raybrarian** [open-oni/open-oni#601]
Need to spend **at most a day or two** researching Django best practices to support Scoop talking to Open ONI via API for managerial tasks. Essentially, can we use Django management commands  (manage.py) over API? This includes load batch, purge batch, etc. - we want to be able to securely expose the underlying processes so that command line invocation isn't needed. This should also be a controlled set of actions. 

Marking this for discussion between Greg and Jeremy.

**Comment by techgique** [comment]
Research notes

- No pre-existing projects that have been maintained in recent history
  - https://github.com/skibblenybbles/django-commando - Last updated 2014 and archived
  - https://github.com/tarequeh/django-management-api - Last updated 2013
- Built-in Django auth looks like it is just for web and CRUD control for model objects
- Django REST Framework (https://www.django-rest-framework.org/) looks like the most straightforward tool for our needs
  - Provides token authentication like we use for SFTPGo as well as many other auth types - https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication
  - Permissions for access control - https://www.django-rest-framework.org/api-guide/permissions/
  - Throttling - https://www.django-rest-framework.org/api-guide/throttling/
  - Very active and well documented
- Looked into Celery as task queuing infrastructure if we need additional tools to manage execution of the management commands
  - Celery - https://docs.celeryq.dev/en/stable/
    - https://arocketman.medium.com/distributed-task-queue-with-python-using-celery-and-fastapi-4cd1ad112c0f
  - Flower adds a REST API which could be used to queue tasks - https://flower.readthedocs.io/en/latest/index.html
  - This isn't as focused on the primary functionality we're looking for and is a much heavier dependency to add as it also requires RabbitMQ or similar server daemon running; Also may largely be redundant to the job queueing already in NCA

Closing and continuing with epic issue: https://github.com/open-oni/open-oni/issues/602
