### ISSUE TITLE
Solr 9 Default Highlighting Change

### ISSUE THREAD

**Issue by techgique** [open-oni/open-oni#623]
Jeremy first found this a while ago when searches were returning "(Alcohol" in highlighted results rather than just "Alcohol" for a search of "alcohol" with Solr 9. He later tested with Solr 8 and Solr 9 to compare and found for a search of "apples" and "alcohol":

- Solr 8 returns `<em>Appling</em> (<em>Alcohol</em>...`
- Solr 9 returns `<em>Appling (Alcohol</em>...`

Jeremy found Solr documentation notes that Solr 9's default highlight method changes to the "unified" method rather than Solr 8 and below using the "original" method. Unified has been available since Solr 6.4. Jeremy submitted a [hotfix PR](https://github.com/open-oni/open-oni/pull/622) to hardcode using the "original" method for continuity in Open ONI behavior.

I've been testing with our [sample data batches](https://github.com/open-oni/sample-data) and read that [Unified Highlighting supposed to be more efficient and avoid over-highlighting](https://solr.apache.org/guide/solr/latest/query-guide/highlighting.html#choosing-a-highlighter). But I've also found that Unified Highlighting seems to over-highlight and include extra words and special characters in Open ONI search results. An issue hadn't been created so I wanted to document the issue for posterity here and share how I tested the behavior.

I found searches for "water gas", "transact business", and "republican second" on the sample batches demonstrate the issue of over-highlighting. This seems to particularly come from the list of words matching a search being expanded with the default Solr 9 highlighting method. This can be seen in the URL for the page matches on the search results page and in the highlighting on the page image.

- Searching for "water gas"
  - Solr 8 doesn't add anything extra to the search words
    - /lccn/sn83045462/1861-07-19/ed-1/seq-1/#words=Gas+Water
    - ![image](https://github.com/open-oni/open-oni/assets/8347732/3e576826-d032-467d-9db3-ce8763923cea)
  - Solr 9 adds extra words and permutations of the order of words
    - /lccn/sn83045462/1861-07-19/ed-1/seq-1/#words=Gas+and+Water+Water+and+Gas
    - ![image](https://github.com/open-oni/open-oni/assets/8347732/038f6118-4594-4a75-ad93-acd3c5a49b77)

- Searching for "transact business"
  - Solr 8 uses stemming to add some variations of the words
    - /lccn/sn99021999/1887-03-09/ed-1/seq-1/#words=busi+business+transact+transacted+transacting+transaction
    - ![image](https://github.com/open-oni/open-oni/assets/8347732/ab1d7662-b196-4f8e-9e23-2a97702adeb8)
  - Solr 9 adds extra and unusual word matches like "is" and "its"
    - /lccn/sn99021999/1887-03-09/ed-1/seq-1/#words=business+is+transacted+transact+busi+transact+business+transacting+its+busi
    - ![image](https://github.com/open-oni/open-oni/assets/8347732/267bd0a2-4258-4876-8033-25f7eaa590db)

- Searching for "republican second" aims to show the special character issue as "Gardner (Republican) seconded" is text on one page
  - Solr 8 matches "republican seconded"
    - /lccn/sn99021999/1887-03-03/ed-1/seq-1/#words=republican+seconded
    - ![image](https://github.com/open-oni/open-oni/assets/8347732/d5e8a9a1-48ed-437d-8aca-b07b020dbf51)
  - Solr 9 adds the parenthesis to matching words
    - /lccn/sn99021999/1887-03-03/ed-1/seq-1/#words=republican+%29+seconded
    - ![image](https://github.com/open-oni/open-oni/assets/8347732/ae7a5971-08ee-4140-b4b3-5fb977db63a2)

So we'll be moving forward with the restoration of previous behavior rather than the new Solr 9 default highlighting behavior.

**Comment by techgique** [comment]
Addressed with the #622 hotfix PR

**Comment by jechols** [comment]
Wow, thanks for this! Very exhaustive research, I wasn't sure it would be easy to reproduce my findings since I stumbled onto things by dumb luck: one of our favorite articles is a long ago ad in which a "doctor" claims you should eat apples because they prevent alcoholism 🤣
