### ISSUE TITLE
Investigate requirements.pip

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#7]
https://github.com/open-oni/open-oni/blob/master/requirements.pip

What do we have to have?  Probably look at this with django update in mind (south might go away?)

**Comment by jechols** [comment]
Look at hard-coded versions and figure out if we can un-hardcode or what

**Comment by duncanbarth** [comment]
Also determine whether libraries are still being maintained, what the latest versions are, and  compatibility breakages

**Comment by techgique** [comment]
Addressed by #209
