### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#75]
We have a lot of ways to make logging better.  From easiest to hardest, here's what I see:
- Move all task logs to `/opt/openoni/logs` by prefixing `log_file` with said path in `core/management/commands/__init__.py`
- Make above change, but with a log path pulled from settings; fix all log files to be timestamped  Some clobber the previous log, some use pid to identify themselves.
- Figure out how to send all django logs to something like logstash, and add that to the docker stack
- Do the logstash stuff but make it optional so a user can choose a path for individual logs or logstash

Probably worth adding some logrotate config to the main docker container in most of these scenarios.

**Comment by jechols** [comment]
First two bullet points were taken care of by pr #178

**Comment by jduss4** [comment]
@techgique would this be related to anything you are working on?
