### ISSUE TITLE
Offer a way to fix place metadata

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#83]
We're seeing that fixing data is `core_places` is practically mandatory.  We need to figure out what we can do to make that not require users to manually edit the database.

This would require an administrative area for somebody to log into the site and modify city name, etc.  It _may_ be a good idea to allow merging records where the two places are the same, but have different ways to spell something (bad metadata most likely).  I could see that going sideways really horribly, though, so we'd need to be very careful.

**Comment by karindalziel** [comment]
This could maybe also be done via text files (YAML or something to keep it simple) but I agree that an admin interface would be best.
