### ISSUE TITLE
Possibly add explanation text to multi selects

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#91]
After upgrading Django, this explanatory text will no longer show up automatically, so if we want it we'll need to add it to the templates. 

https://docs.djangoproject.com/en/1.8/releases/1.6/#help-text-of-model-form-fields-for-manytomanyfield-fields

![screen shot 2016-01-27 at 3 49 19 pm](https://cloud.githubusercontent.com/assets/284315/12629573/1775d506-c50e-11e5-8f89-a8e3c4e8516a.png)

**Comment by jduss4** [comment]
https://github.com/open-oni/open-oni/commit/55df97a5161b53e17bf7b15778d9b31b8b7eaaca
