### ISSUE TITLE
Loading same batch under different name

### ISSUE THREAD

**Issue by jduss4** [open-oni/open-oni#92]
If you load a batch twice, but fool the loader with a different batch name, there are some consequences.  Though /batches will correctly record the batches you have loaded...
- /newspapers reports incorrect number of issues
- /languages/ger/title shows the title twice (see attached image)
- /have not tried to purge one batch at this point, could be side effects there, also

It seems to be duplicating all the shared titles, issues, pages, which is probably not desirable behavior.  At the same time, it is not polite behavior to double load a batch, so maybe that's our problem.

![pasted image at 2016_01_27 03_51 pm](https://cloud.githubusercontent.com/assets/2480492/12629714/ad81582c-c50e-11e5-8929-a08d1ff8159f.png)

**Comment by jechols** [comment]
I think this should be an issue-level thing.  If two batches only contain a single issue in common, that's still cause for concern.  Seems like checking the issues for dupes prior to ingest could be slow, but very valuable as we (UO) do a lot of born-digital and in-house work.

**Comment by raybrarian** [comment]
Now unable to ingest dupes - closing.

**Comment by jechols** [comment]
ONI definitely allows ingesting dupes - this needs to be reopened

**Comment by jechols** [comment]
I've opened a new issue linked to this one which hopefully explains the problem a bit better. So this can be closed now.
