### ISSUE TITLE
Remove US Newspaper Directory and associated pages

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#93]
Can we remove the open-oni equivalent of this page: http://chroniclingamerica.loc.gov/search/titles/?

The associated templates are:

* core/templates/news_directory.html
* core/template/titles.html
* core/templates/search/search_titles_results.html

I think if we want users to have access to this feature we can just link to chronicling america.

**Comment by karindalziel** [comment]
@kestlund would love your input on this

**Comment by srabun** [comment]
@karindalziel I would vote yes remove this

**Comment by edsu** [comment]
:+1: @dbrunton always wanted to make the directory a separate app, but we never got around to it

**Comment by kestlund** [comment]
:+1: to remove.

There were a couple of proponents to keep it in the NDNP community; however, they also aren't the folks who would opt for an open source solution. I say axe it!

**Comment by jduss4** [comment]
Discussion around this in the slack group indicates that we probably want to keep searching by newspaper title (not listing all the NDNP titles, however).  search/titles and the results page will need to be revisited for styling concerns if we are keeping the title search.

**Comment by jduss4** [comment]
https://github.com/open-oni/open-oni/issues/180

**Comment by jduss4** [comment]
It sounds like removing this will be put off until the title search is folded into the newspaper browse view, right?
