### ISSUE TITLE
delete "topics" section

### ISSUE THREAD

**Issue by karindalziel** [open-oni/open-oni#94]
Can we get rid of this section: http://www.loc.gov/rr/news/topics/topics.html

"Chronicling America provides free access to millions of historic American newspaper pages. Listed here are topics widely covered in the American press of the time. We will be adding more topics on a regular basis." 

We can just link to the LOC if we want o users to have access.

Associated templates: 
* core/template/topics_list.html
* core/template/topic.html
* core/templates/page_print.html

**Comment by karindalziel** [comment]
@kestlund would love your input on this

**Comment by srabun** [comment]
@karindalziel I think it's fine to remove this

**Comment by kestlund** [comment]
:+1: remove!

**Comment by windrant** [comment]
I say remove. We're building a similar thing for New York with state specific topics but that's part of our K-12 education initiative. I don't think a new open-oni install would need that.

**Comment by karindalziel** [comment]
When I created the issue, I was thinking only about templates. Removing the rest sounds like a larger project and isn't necessarily high priority. The reason I think removing the templates is higher is this is the part that non technical people will likely touch, and I don't want confusing broken things in there.

**Comment by jduss4** [comment]
https://github.com/open-oni/open-oni/pull/165
